version: "3.4"
services: 
  web: 
    image: ubuntu:airflow_stack
    healthcheck: 
      interval: 30s
      retries: 3
      test:
        - CMD-SHELL
        - "[ -f /usr/local/airflow/airflow-webserver.pid ]"
      timeout: 30s
      start_period: 30s
    ports: 
      - 8085:8085
    networks:
      - merapbi
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
    volumes: 
      - "./dags:/usr/local/airflow/dags"
      - "./plugins:/usr/local/airflow/plugins"
networks:
  merapbi:
    external: true