# -*- coding: utf-8 -*-
"""healthcheck.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/18AT168oqhjyRqc2X3WQg181bv43Fq9bB
"""

import requests
import sys
r = requests.get("http://171.235.26.161:8085/health")

if r.json()['scheduler']['status'] == 'unhealthy': sys.exit(1)
else: sys.exit(0)

