# -*- coding: utf-8 -*-
"""capture.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1CCYGw0oM5GsmRI75MSXllw4ERjO389oS
"""

from utils.df_handle import *


from utils.df_handle import *
import pendulum
from airflow import DAG
from airflow.operators.dummy_operator import DummyOperator
from airflow.operators.python_operator import PythonOperator
from airflow.providers.tableau.operators.tableau_refresh_workbook import TableauRefreshWorkbookOperator
from airflow.providers.postgres.hooks.postgres import PostgresHook
from airflow.providers.microsoft.mssql.hooks.mssql import MsSqlHook


local_tz = pendulum.timezone("Asia/Bangkok")

name='Capture_notoihan_mds'
prefix='Debt_'
csv_path = '/usr/local/airflow/plugins'+'/'

capture_sql = \
"""
SELECT slsperid,slspername,tenquanlytt,tenquanlyvung,tenquanlykhuvuc, terms, sum(tiennocongty) as tiennocongty,updated_at from (
	SELECT a.branchid,a.ordernbr,a.slsperid,a.slspername,c.tenquanlytt,c.tenquanlyvung,c.tenquanlykhuvuc,a.supname,a.asmname,a.dateoforder as ngaydatdon,
	Case when deli_last_updated ='1900-01-01 00:00:00' then now() -interval '1day' else deli_last_updated end
	as ngaygiaohang, a.custid,a.custname,b.tinh,a.terms,a.inchargename,a.tienchotso,a.tiengiaothanhcong,a.tiennocongty,a.tienthuquyxacnhan,a.duedate,
	Case when trangthaigiaohang ='NaN' then 'Chưa Xác Nhận' else a.trangthaigiaohang end as trangthaigiaohang,
	 
	--  Case when 
	--  EXTRACT('hour' from a.deli_last_updated) in (0,1,2,3,4,5,6,7,8,9,10,11) then date(a.deli_last_updated) + "interval" '16 hour' 
	-- when
	--  EXTRACT('hour' from a.deli_last_updated) in (12,13,14,15,16,17,18,19,20,21,22,23) then date(a.deli_last_updated) + "interval"' 10 hour' + interval '1 day'  else now() end as ngaytoihan1,
	Case when trim(f.tencvbh) = trim(c.tenquanlykhuvuc) then f.email else 'nhanvt92@gmail.com'end as email_mng,
	Case when trim(e.tencvbh) = trim(c.tenquanlytt) then e.email else 'bimerap.main@gmail.com' end as email_sup,
	Case when trim(d.tencvbh) = trim(a.slspername) then d.email else 'bimerap.main@gmail.com' end as email_staff,
	Case 
		-- when a.terms = 'Gối 1 Đơn Hàng (trong 30 ngày)' then date(duedate)
		when trangthaigiaohang ='Đã giao hàng' 
		and terms in ('Thu tiền ngay không có VP PN','Thu tiền ngay có VP PN','Gối Đầu 30 Pha Nam')
		 	 then date(a.deli_last_updated) + interval '1 day'	 	
	    when trangthaigiaohang not in ('Đã giao hàng') and a.terms in ('Thu tiền ngay không có VP PN' ,'Gối Đầu 30 Pha Nam') --,'Gối Đầu 30 Pha Nam'
			 then date(dateoforder) + interval '2 day' 
		when trangthaigiaohang not in ('Đã giao hàng') and a.terms in ('Thu tiền ngay có VP PN')
			 then date(dateoforder) + interval '1 day' 
	else date(duedate)
	end as ngaytoihan1,
	--date(duedate) as ngaytoihan1,
	Case when 
	( a.terms not in ('Thu tiền ngay có VP PN','Thu tiền ngay không có VP PN','Gối Đầu 30 Pha Nam') 
	and date(duedate) <= date(now()) )
	or
	( a.trangthaigiaohang = 'Đã giao hàng'and terms in ('Thu tiền ngay không có VP PN','Thu tiền ngay có VP PN','Gối Đầu 30 Pha Nam') 
	 and date(a.deli_last_updated) + interval '1 day' <= date(now())
     
	 )
	
	or ( trangthaigiaohang not in ('Đã giao hàng') and a.terms in ('Thu tiền ngay không có VP PN','Gối Đầu 30 Pha Nam') --,'Gối Đầu 30 Pha Nam'
	and date(dateoforder) + interval '2 day' <= date(now()) ) 

	or (trangthaigiaohang not in ('Đã giao hàng') and a.terms in ('Thu tiền ngay có VP PN')
	and date(dateoforder) + interval '1 day' <= date(now()) )
	
	then 'Đã tới hạn' else 'Chưa tới hạn' end as no_toi_han,
	a.inserted_at  as updated_at

	from f_tracking_debt a
	LEFT JOIN d_kh b on a.custid = b.custid
	LEFT JOIN d_users c on c.manv =a.slsperid
	LEFT JOIN d_takeorder_phanquyenstaff d on trim(d.tencvbh) = trim(a.slspername)
	LEFT JOIN d_takeorder_phanquyenstaff e on trim(e.tencvbh) = trim(c.tenquanlytt)
	LEFT JOIN d_takeorder_phanquyenstaff f on trim(f.tencvbh) = trim(c.tenquanlykhuvuc)
	where 
	(
	--terms in ('Thu tiền ngay có VP PN','Thu tiền ngay không có VP PN','Gối 1 Đơn Hàng (trong 30 ngày)','Gối Đầu 30 Pha Nam')  
	--and a.paymentsform ='TM'--
	--and 
	debtincharge_v2 ='MDS'  and tiennocongty > 1000 and a.slsperid <> 'GH001'
	) 
	) a
	where no_toi_han ='Đã tới hạn'
	GROUP BY 
slsperid,slspername,tenquanlytt,tenquanlyvung,tenquanlykhuvuc, terms,updated_at
ORDER BY slspername
"""


dag_params = {
    'owner': 'nhanvo',
    "depends_on_past": False,
    'start_date': datetime(2021, 10, 1, tzinfo=local_tz),
    # 'email_on_failure': True,
    # 'email_on_retry': False,
    # 'email':['duyvq@merapgroup.com', 'vanquangduy10@gmail.com'],
    'do_xcom_push': False,
    'execution_timeout':timedelta(seconds=300)
    # 'retries': 3,
    # 'retry_delay': timedelta(minutes=10),
}

dag = DAG(prefix+name,
          catchup=False,
          default_args=dag_params,
          schedule_interval= '0 19 * * *',
          tags=[prefix+name, 'Daily', 'at19']
)

def update_table():
	df = get_ps_df(capture_sql)
	bq_values_insert(df, "f_daily_capture_notoihan_taixe", 2)
	pk = ['slsperid','updated_at','terms']
	execute_values_upsert(df, "f_daily_capture_notoihan_taixe",pk)

dummy_start = DummyOperator(task_id="dummy_start", dag=dag)

py_update_table = PythonOperator(task_id="update_table", python_callable=update_table, dag=dag)


dummy_start >> py_update_table 

