# -*- coding: utf-8 -*-
"""f_sales_pend.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1Gv4TJMgxnLP4CFit3NFDFF8kjnBH9Ci6
"""

# DON'T USE THIS CELL
from utils.df_handle import *
import pendulum
from airflow import DAG
from airflow.models import Variable
from airflow.operators.dummy_operator import DummyOperator
from airflow.operators.python_operator import PythonOperator
import requests
from requests.structures import CaseInsensitiveDict
from openpyxl import Workbook, load_workbook
from datetime import datetime  
from datetime import timedelta 

local_tz = pendulum.timezone("Asia/Bangkok")
name='Logpharma'
prefix='Crawl_'
path = f'/usr/local/airflow/plugins/{prefix}{name}/'

# datenow_min1 = (datetime.now() - timedelta(days=1)).strftime("%Y-%m-%d")

dag_params = {
    'owner': 'phuonght2',
    "depends_on_past": False,
    'start_date': datetime(2022, 7, 15, tzinfo=local_tz),
    # 'email_on_failure': True,
    # 'email_on_retry': False,
    # 'email':['duyvq@merapgroup.com', 'vanquangduy10@gmail.com'],
    'do_xcom_push': False,
    'execution_timeout':timedelta(seconds=300)
    # 'retries': 3,
    # 'retry_delay': timedelta(minutes=10),
}

dag = DAG(prefix+name,
          catchup=False,
          default_args=dag_params,
          schedule_interval= '0 7 * * *',
          tags=[prefix+name, 'Daily', '7hour']
)

# fdom = datetime.now().replace(day=1).strftime("%Y%m%d")
# datenow = datetime.now().strftime("%Y%m%d")
# datenow_add1 = (datetime.now() + timedelta(1)).strftime("%Y%m%d")

day1 = datetime.now() - timedelta(days = 1)
day3 = datetime.now() - timedelta(days = 4)
day1 = day1.strftime("%Y-%m-%d")
day3 = '2022-07-18'#day3.strftime("%Y-%m-%d")
day4 = '2022-08-01'#day3.strftime("%Y-%m-%d")
day5 = '2022-07-01'#day3.strftime("%Y-%m-%d")

day1a = datetime.now() - timedelta(days = 1)
day1a = day1a.strftime("%Y%m%d")
current_time=(datetime.now()- timedelta(hours = 7)).strftime("%Y-%m-%d %H:%M:%S")

session_id = Variable.get("logpharma_session_id", None)

session_hcm=session_id
session_dnai=session_id
session_ct=session_id

def extract_hcm():
    # url= """https://giaoduocpham.com/report/xlsx/rebase_field_service.stock_delivery_customer_xlsx?options={"form":{"date_from":"2022-07-18","date_to":"2022-07-21","select_date":"today","company_id":1,"display_name":"stock.delivery.customer.report,6700","create_uid":412,"write_date":"2022-07-19 10:01:03","id":6700,"customer_ids":[73069],"__last_update":"2022-07-19 10:01:03","create_date":"2022-07-19 10:01:03","write_uid":412},"model":"stock.delivery.customer.report","ids":[]}&context={"tz":"Asia/Ho_Chi_Minh","lang":"vi_VN","uid":412,"xls_export":1,"active_model":"stock.delivery.customer.report","active_id":6700,"active_ids":[6700]}"""
    # url1 = """https://giaoduocpham.com/report/xlsx/rebase_field_service.stock_delivery_customer_xlsx?options={"form":{"date_from":"%s""" %(day3)+"""","date_to":"%s""" %(day1)+"""","select_date":"today","company_id":1,"display_name":"stock.delivery.customer.report,6826","create_uid":412,"write_date":"2022-08-01 04:18:41","id":6826,"customer_ids":[73069],"__last_update":"2022-08-01 04:18:41","create_date":"2022-08-01 04:18:41","write_uid":412},"model":"stock.delivery.customer.report","ids":[]}&context={"tz":"Asia/Ho_Chi_Minh","lang":"vi_VN","uid":412,"xls_export":1,"active_model":"stock.delivery.customer.report","active_id":6826,"active_ids":[6826]}"""
    url_hcm = """https://giaoduocpham.com/report/xlsx/rebase_field_service.stock_delivery_customer_xlsx?options={"form":{"date_from":"%s""" %(day3)+"""","date_to":"%s""" %(day1)+"""","select_date":"today","company_id":1,"display_name":"stock.delivery.customer.report,6826","create_uid":412,"write_date":"%s""" %(current_time)+"""","id":6826,"customer_ids":[73069],"__last_update":"%s""" %(current_time)+"""","create_date":"%s""" %(current_time)+"""","write_uid":412},"model":"stock.delivery.customer.report","ids":[]}&context={"tz":"Asia/Ho_Chi_Minh","lang":"vi_VN","uid":412,"xls_export":1,"active_model":"stock.delivery.customer.report","active_id":6826,"active_ids":[6826]}"""

    print("URLHCM is ", url_hcm)

    headers = CaseInsensitiveDict()
    headers['authority'] = 'giaoduocpham.com'
    headers['cookie'] = f'session_id={session_hcm}; frontend_lang=vi_VN; fileToken=dummy-because-api-expects-one'
    headers['origin'] = 'https://giaoduocpham.com'
    headers['referer'] = 'https://giaoduocpham.com/web'
    headers['user-agent'] = 'Mozilla/5.0 (Linux; Android 6.0; Nexus 5 Build/MRA58N) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/103.0.0.0 Mobile Safari/537.36'
    resp = requests.get(url_hcm, headers=headers)
    print("r_content ii ", resp.content)
    with open(path+f"""filename_goc_hcm_{day1a}.xlsx""", 'wb') as output:
        output.write(resp.content)

    wb = load_workbook(path+f"""filename_goc_hcm_{day1a}.xlsx""")
    ws =  wb.active
    for merge in list(ws.merged_cells):
        ws.unmerge_cells(range_string=str(merge))
    ws.delete_rows(1,11)
    wb.save(path+f"""filename_hcm_{day1a}.xlsx""")

def extract_dnai():
    # url= """https://giaoduocpham.com/report/xlsx/rebase_field_service.stock_delivery_customer_xlsx?options={"form":{"date_from":"2022-07-18","date_to":"2022-07-21","select_date":"today","company_id":1,"display_name":"stock.delivery.customer.report,6700","create_uid":412,"write_date":"2022-07-19 10:01:03","id":6700,"customer_ids":[73069],"__last_update":"2022-07-19 10:01:03","create_date":"2022-07-19 10:01:03","write_uid":412},"model":"stock.delivery.customer.report","ids":[]}&context={"tz":"Asia/Ho_Chi_Minh","lang":"vi_VN","uid":412,"xls_export":1,"active_model":"stock.delivery.customer.report","active_id":6700,"active_ids":[6700]}"""
    # url1 = """https://giaoduocpham.com/report/xlsx/rebase_field_service.stock_delivery_customer_xlsx?options={"form":{"date_from":"%s""" %(day3)+"""","date_to":"%s""" %(day1)+"""","select_date":"today","company_id":1,"display_name":"stock.delivery.customer.report,6826","create_uid":412,"write_date":"2022-08-01 04:18:41","id":6826,"customer_ids":[73069],"__last_update":"2022-08-01 04:18:41","create_date":"2022-08-01 04:18:41","write_uid":412},"model":"stock.delivery.customer.report","ids":[]}&context={"tz":"Asia/Ho_Chi_Minh","lang":"vi_VN","uid":412,"xls_export":1,"active_model":"stock.delivery.customer.report","active_id":6826,"active_ids":[6826]}"""
    url_dnai = """https://giaoduocpham.com/report/xlsx/rebase_field_service.stock_delivery_customer_xlsx?options={"form":{"date_from":"%s""" %(day4)+"""","date_to":"%s""" %(day1)+"""","select_date":"today","company_id":1,"display_name":"stock.delivery.customer.report,6826","create_uid":412,"write_date":"%s""" %(current_time)+"""","id":6826,"customer_ids":[68340],"__last_update":"%s""" %(current_time)+"""","create_date":"%s""" %(current_time)+"""","write_uid":412},"model":"stock.delivery.customer.report","ids":[]}&context={"tz":"Asia/Ho_Chi_Minh","lang":"vi_VN","uid":412,"xls_export":1,"active_model":"stock.delivery.customer.report","active_id":6826,"active_ids":[6826]}"""

    print("URLDNAI is ", url_dnai)

    headers = CaseInsensitiveDict()
    headers['authority'] = 'giaoduocpham.com'
    headers['cookie'] = f'session_id={session_dnai}; frontend_lang=vi_VN; fileToken=dummy-because-api-expects-one'
    headers['origin'] = 'https://giaoduocpham.com'
    headers['referer'] = 'https://giaoduocpham.com/web'
    headers['user-agent'] = 'Mozilla/5.0 (Linux; Android 6.0; Nexus 5 Build/MRA58N) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/103.0.0.0 Mobile Safari/537.36'
    resp = requests.get(url_dnai, headers=headers)
    print("r_content ii ", resp.content)
    with open(path+f"""filename_goc_dnai_{day1a}.xlsx""", 'wb') as output:
        output.write(resp.content)

    wb = load_workbook(path+f"""filename_goc_dnai_{day1a}.xlsx""")
    ws =  wb.active
    for merge in list(ws.merged_cells):
        ws.unmerge_cells(range_string=str(merge))
    ws.delete_rows(1,11)
    wb.save(path+f"""filename_dnai_{day1a}.xlsx""")

def extract_ct():
    # url= """https://giaoduocpham.com/report/xlsx/rebase_field_service.stock_delivery_customer_xlsx?options={"form":{"date_from":"2022-07-18","date_to":"2022-07-21","select_date":"today","company_id":1,"display_name":"stock.delivery.customer.report,6700","create_uid":412,"write_date":"2022-07-19 10:01:03","id":6700,"customer_ids":[73069],"__last_update":"2022-07-19 10:01:03","create_date":"2022-07-19 10:01:03","write_uid":412},"model":"stock.delivery.customer.report","ids":[]}&context={"tz":"Asia/Ho_Chi_Minh","lang":"vi_VN","uid":412,"xls_export":1,"active_model":"stock.delivery.customer.report","active_id":6700,"active_ids":[6700]}"""
    # url1 = """https://giaoduocpham.com/report/xlsx/rebase_field_service.stock_delivery_customer_xlsx?options={"form":{"date_from":"%s""" %(day3)+"""","date_to":"%s""" %(day1)+"""","select_date":"today","company_id":1,"display_name":"stock.delivery.customer.report,6826","create_uid":412,"write_date":"2022-08-01 04:18:41","id":6826,"customer_ids":[73069],"__last_update":"2022-08-01 04:18:41","create_date":"2022-08-01 04:18:41","write_uid":412},"model":"stock.delivery.customer.report","ids":[]}&context={"tz":"Asia/Ho_Chi_Minh","lang":"vi_VN","uid":412,"xls_export":1,"active_model":"stock.delivery.customer.report","active_id":6826,"active_ids":[6826]}"""
    url_ct = """https://giaoduocpham.com/report/xlsx/rebase_field_service.stock_delivery_customer_xlsx?options={"form":{"date_from":"%s""" %(day3)+"""","date_to":"%s""" %(day1)+"""","select_date":"today","company_id":1,"display_name":"stock.delivery.customer.report,6826","create_uid":412,"write_date":"%s""" %(current_time)+"""","id":6826,"customer_ids":[131717],"__last_update":"%s""" %(current_time)+"""","create_date":"%s""" %(current_time)+"""","write_uid":412},"model":"stock.delivery.customer.report","ids":[]}&context={"tz":"Asia/Ho_Chi_Minh","lang":"vi_VN","uid":412,"xls_export":1,"active_model":"stock.delivery.customer.report","active_id":6826,"active_ids":[6826]}"""

    print("URLCT is ", url_ct)

    headers = CaseInsensitiveDict()
    headers['authority'] = 'giaoduocpham.com'
    headers['cookie'] = f'session_id={session_ct}; frontend_lang=vi_VN; fileToken=dummy-because-api-expects-one'
    headers['origin'] = 'https://giaoduocpham.com'
    headers['referer'] = 'https://giaoduocpham.com/web'
    headers['user-agent'] = 'Mozilla/5.0 (Linux; Android 6.0; Nexus 5 Build/MRA58N) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/103.0.0.0 Mobile Safari/537.36'
    resp = requests.get(url_ct, headers=headers)
    print("r_content ii ", resp.content)
    with open(path+f"""filename_goc_ct_{day1a}.xlsx""", 'wb') as output:
        output.write(resp.content)

    wb = load_workbook(path+f"""filename_goc_ct_{day1a}.xlsx""")
    ws =  wb.active
    for merge in list(ws.merged_cells):
        ws.unmerge_cells(range_string=str(merge))
    ws.delete_rows(1,11)
    wb.save(path+f"""filename_ct_{day1a}.xlsx""")


def update_giaoduocpham():

    # extract_hcm()
    # extract_dnai()
    # extract_ct()


    file_hcm = path+f"""filename_hcm_{day1a}.xlsx"""
    file_dnai = path+f"""filename_dnai_{day1a}.xlsx"""
    file_ct = path+f"""filename_ct_{day1a}.xlsx"""


    print("handle hcm")
    df_hcm=pd.read_excel(file_hcm)
    df_hcm.columns= lower_col(df_hcm)
    df_hcm.columns=cleancols(df_hcm)
    df_hcm=df_hcm[~df_hcm['donhang'].isna()]
    df_hcm['ngayhoanthanh']=pd.to_datetime(df_hcm['ngayhoanthanh'], format="%d-%m-%Y %H:%M:%S")
    df_hcm['ngaytao']=pd.to_datetime(df_hcm['ngaytao'], format="%d-%m-%Y %H:%M:%S")
    df_hcm[['branchid','reportid']] = df_hcm.manbchuhang.str.split(pat='\t',expand=True)
    df_hcm['branch'] = 'hcm'

    print("handle dnai")
    df_dnai=pd.read_excel(file_dnai)
    df_dnai.columns= lower_col(df_dnai)
    df_dnai.columns=cleancols(df_dnai)
    df_dnai=df_dnai[~df_dnai['donhang'].isna()]
    df_dnai['ngayhoanthanh']=pd.to_datetime(df_dnai['ngayhoanthanh'], format="%d-%m-%Y %H:%M:%S")
    df_dnai['ngaytao']=pd.to_datetime(df_dnai['ngaytao'], format="%d-%m-%Y %H:%M:%S")
    df_dnai['branchid'] = df_dnai.manbchuhang.str.strip().str[0:6]
    df_dnai['reportid'] = df_dnai.manbchuhang.str.strip().str[6:]
    # df_dnai[['branchid','reportid']] = df_dnai.manbchuhang.str.split(pat='\t',expand=True)
    df_dnai['branch'] = 'dnai'

    print("handle ct")
    df_ct=pd.read_excel(file_ct)
    df_ct.columns= lower_col(df_ct)
    df_ct.columns=cleancols(df_ct)
    df_ct=df_ct[~df_ct['donhang'].isna()]
    df_ct['ngayhoanthanh']=pd.to_datetime(df_ct['ngayhoanthanh'], format="%d-%m-%Y %H:%M:%S")
    df_ct['ngaytao']=pd.to_datetime(df_ct['ngaytao'], format="%d-%m-%Y %H:%M:%S")
    df_ct['branchid'] = df_ct.manbchuhang.str.strip().str[0:6]
    df_ct['reportid'] = df_ct.manbchuhang.str.strip().str[6:]
    # df_ct[['branchid','reportid']] = df_ct.manbchuhang.str.split(pat='\t',expand=True)
    df_ct['branch'] = 'ct'

    print("union_all")
    df=union_all([df_hcm,df_dnai])
    df=union_all([df,df_ct])
    bq_values_insert(df,"d_crawl_logpharma",3)   


# Dont Execute this
dummy_start = DummyOperator(task_id="dummy_start", dag=dag)

extract_hcm = PythonOperator(task_id="extract_hcm", python_callable=extract_hcm, dag=dag)

extract_dnai = PythonOperator(task_id="extract_dnai", python_callable=extract_dnai, dag=dag)

extract_ct = PythonOperator(task_id="extract_ct", python_callable=extract_ct, dag=dag)

update_giaoduocpham = PythonOperator(task_id="update_giaoduocpham", python_callable=update_giaoduocpham, dag=dag)

dummy_start >> extract_hcm >> extract_dnai >> extract_ct>> update_giaoduocpham