# -*- coding: utf-8 -*-
"""f_sales_pend.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1Gv4TJMgxnLP4CFit3NFDFF8kjnBH9Ci6
"""

# # DON'T USE THIS CELL
from utils.df_handle import *
import pendulum
from airflow import DAG
from airflow.operators.dummy_operator import DummyOperator
from airflow.operators.python_operator import PythonOperator
import io
import shutil
from google.oauth2 import service_account
from googleapiclient import discovery
from googleapiclient.http import MediaFileUpload, MediaIoBaseDownload
from cmath import nan

local_tz = pendulum.timezone("Asia/Bangkok")
name='DocsController'
prefix='update_'
path = f'/usr/local/airflow/plugins/update_hr_data/'#--{prefix}{name}/'

# datenow_min1 = (datetime.now() - timedelta(days=1)).strftime("%Y-%m-%d")

dag_params = {
    'owner': 'phuonght2',
    "depends_on_past": False,
    'start_date': datetime(2022, 4, 28, tzinfo=local_tz),
    # 'email_on_failure': True,
    # 'email_on_retry': False,
    # 'email':['duyvq@merapgroup.com', 'vanquangduy10@gmail.com'],
    'do_xcom_push': False,
    'execution_timeout':timedelta(seconds=300)
    # 'retries': 3,
    # 'retry_delay': timedelta(minutes=10),
}

dag = DAG(prefix+name,
          catchup=False,
          default_args=dag_params,
          schedule_interval= '0 8-23 * * *',
          tags=[prefix+name, 'Daily', '60mins']
)

# fdom = datetime.now().replace(day=1).strftime("%Y%m%d")
# datenow = datetime.now().strftime("%Y%m%d")
# datenow_add1 = (datetime.now() + timedelta(1)).strftime("%Y%m%d")

def DocsController_data():
    file = pd.read_csv("https://docs.google.com/spreadsheets/d/e/2PACX-1vS_SqGlVlQObBecB9isKfAFEtWZpacuNrrMfh8uj1KeFnYNS_J7o_kxiFvirhf1BXOsI3OKd626uwkc/pub?gid=0&single=true&output=csv")
    file.columns = lower_col(file)
    cleancols(file)
    scopes = ['https://www.googleapis.com/auth/spreadsheets', 
        'https://www.googleapis.com/auth/drive',
        'https://www.googleapis.com/auth/drive.file']
    jsonfile = path+'datateam.json'
    credentials = service_account.Credentials.from_service_account_file(jsonfile, scopes=scopes)
    service = discovery.build('drive', 'v3', credentials=credentials)


    file_id = '1EmMS46usylDzxDrKzteFQk2XzlZEMGpD'

    fh = io.BytesIO()
    a = service.files().get(fileId='1PS_diwtGgQEdNHhp94bNsqQ0chBU64sO1_AKRZ5wbAY', fields='modifiedTime,name').execute()
    file['file']=a['name']
    file['last_updated']=pd.to_datetime(a['modifiedTime'])
    file['ngaybanhanh']=pd.to_datetime(file['ngaybanhanh'])
    file['thoigianhieuluc']=pd.to_datetime(file['thoigianhieuluc'])
    file['thoigianhethieuluc']=pd.to_datetime(file['thoigianhethieuluc'])

    bq_values_insert(file,"d_doccontroller",3)

        


# Dont Execute this
dummy_start = DummyOperator(task_id="dummy_start", dag=dag)

DocsController_data = PythonOperator(task_id="DocsController_data", python_callable=DocsController_data, dag=dag)


# update_hr_data = PythonOperator(task_id="update_hr_data", python_callable=update_hr_data, dag=dag)

dummy_start >> DocsController_data 